version: '3.8'

services:
  web:
    image: nginx:alpine
    container_name: rs_nginx
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
  php:
    build: ./src
    container_name: rs_php
    volumes:
      - ./src:/var/www/html
    environment:
      DB_HOST: rs_db
      DB_NAME: shopdb
      DB_USER: shopuser
      DB_PASS: shoppass
    depends_on:
      - db
  db:
    image: mysql:8.0
    container_name: rs_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: shopdb
      MYSQL_USER: shopuser
      MYSQL_PASSWORD: shoppass
    ports:
      - "3306:3306"
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
